export const projects = [
  {
    title: "BCards",
    subtitle: "Swift, SwiftUI, UIKit, Firebase",
    description:
      "BCards offer a simple way to create, edit and fully customize your business card. It is available for free on the App Store. Made mainly with SwiftUI. The project includes some Combine pipelines and some UIKit Components like the share sheet. The back-end is handled by Firebase using Firestore and Firebase Auth",
    image: "./ezgif.com-gif-maker.gif",
    link: "https://apps.apple.com/ca/app/bcards/id1569033671",
  },
  {
    title: "FakeShopping-App",
    subtitle: "SwiftUI, Rest API",
    description:
      "The app is fully made in SwiftUI, it uses Fake-Store-API to get the products with a custom category picker. When logged in, a user is randomly generated by Random User Generator",
    image: "./swiftShopping.gif",
    link: "https://github.com/Djallil14/SwiftUI-FakeShopping-App",
  },
  {
    title: "inGENEious",
    subtitle: "Swift, SwiftUI, Swift5.5 Async Await, SwiftSoup, Swift Caching",
    description:
      "InGENEious was made during SwiftUIJAM 2021, i mainly contributed to creating and structuring the networking using new concurency offered by Swift 5.5, as well as providing the UIKit/WebKit part of the app. The app provides a seamless experience in viewing ten genes that are present within the human body. Each gene provides general information within the application itself with an option to retrieve a detailed description by following the prompts.",
    image: "./ingenious.gif",
    link: "https://github.com/raf-fun/DNA-strand",
  },
  {
    title: "Luck'O'Meter",
    subtitle: "Swift, UserDefault Caching, SwiftUI",
    description:
    "Currently in private Test Flight Period. A mix of swift, Swift and UIKit. The app uses the power of SwiftUI Animation and matched geometry to provide 3 beautiful and simple mini-games that rely fully on the user's luck. The app provides a lot of stats about the users like Daily Luck calculated when playing the games and a result page with a global and normalized luck. The app offers a fun way for the users to quantify their luck and post about it on social media.",
    image: "./TestLuck.gif",
    link: "#contact",
  },
];


export const skills = [
  "Swift",
  "SwiftUI",
  "JavaScript",
  "Node",
  "REST API",
  "React",
  "Firebase",
  "UIKit",
  "MapKit",
  "Apollo GraphQL",
  "UICollectionView",
  "UITableView"
];

